name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run check

      - name: Run tests
        run: npm run test

      - name: Collect coverage
        run: npm run test:coverage

      - name: Update coverage badge
        if: github.ref == 'refs/heads/main'
        run: node scripts/update-coverage-badge.mjs

      - name: Commit coverage badge
        if: github.ref == 'refs/heads/main'
        run: |
          if [[ -n "$(git status --porcelain .github/badges/coverage.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .github/badges/coverage.json
            git commit -m "chore: update coverage badge"
            git push
          fi
